# Tags: 6.0-alpine3.14-arm32v7, 6.0-alpine-arm32v7, 6.0.0-alpine3.14-arm32v7
FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine3.14-arm32v7
FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine-arm32v7
FROM mcr.microsoft.com/dotnet/aspnet:6.0.0-alpine3.14-arm32v7
